apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
    name: config-management
    namespace: config-management-system
spec:
  clusterName: <CLUSTER_NAME>
  git:
    syncRepo: <REPO_URL>
    syncBranch: 1.0.0
    secretType: none
    policyDir: "."
    syncWait: 2
  enableAggregateNamespaceQuotas: true
  enableHierarchicalResourceQuota: true