apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
    name: config-management
    namespace: config-management-system
spec:
  clusterName: <CLUSTER_NAME>
  policyController:
    enabled: true
  git:
    syncRepo: <REPO_URL>
    syncBranch: <SYNC_BRANCH>
    secretType: none
    policyDir: <POLICY_DIR>
    syncWait: 2
  enableAggregateNamespaceQuotas: true
  enableHierarchicalResourceQuota: true