kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: usa-fast
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  replication-type: regional-pd
  zones: 
    - us-west1-b
    - us-west1-c
